const express = require("express")
const taskController = require("../controllers/taskController")
const router = express.Router()
router.get("/", taskController.getAllTasks)
router.get("/:id", taskController.getTaskById)
router.post("/", taskController.createTask)
router.put("/", taskController.updateTask)
router.delete("/:id", taskController.deleteTask)
// router.put("/complete/:id", taskController.updateTaskComplete)
module.exports = router