const express = require("express")
const userController = require("../controllers/userController")
const router = express.Router()
router.get("/", userController.getAllUsers)
router.get("/:id", userController.getUserById)
router.post("/", userController.createUser)
router.put("/", userController.updateUser)
router.delete("/:id", userController.deleteUser)
// router.put("/active/:id", userController.updateUserActive)
module.exports = router